version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "src/Bannerlord.ModuleManager.TypeScript"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "src/Bannerlord.ModuleManager.Native.TypeScript"
    schedule:
      interval: "daily"
