name: Publish NPM

on:
  repository_dispatch:
    types: [dotnetjs_types_publish]
  workflow_dispatch:

jobs:
  publish:
    name: Publish on NPM and GPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      
      - name: Setup .NET 6
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 6.0.x
      
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          
      - run: dotnet publish -c Release src/Bannerlord.ModuleManager.WASM
      
      - run: cp ./src/Bannerlord.ModuleManager.WASM/bin/dotnet.* ./src/Bannerlord.ModuleManager.TypeScript/src/lib
      
      - run: |
          cd ./src/Bannerlord.ModuleManager.TypeScript && \
          npm version $(node -p "require('./package.json').version = \
          require('./package.json').version.split('.')[0]+'.' + \
          require('./package.json').version.split('.')[1]+'.' + \
          $(git rev-list --no-merges --count master)") --no-git-tag-version --allow-same-version;
          
      - run: cd ./src/Bannerlord.ModuleManager.TypeScript && npm ci && npm i @butr/dotnet-runtime-ts@*
      
      - run: cd ./src/Bannerlord.ModuleManager.TypeScript && npm run build
      
      - run: cd ./src/Bannerlord.ModuleManager.TypeScript && npm run test
      
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@butr'
      
      - run: cd ./src/Bannerlord.ModuleManager.TypeScript && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM_TOKEN}}

      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@butr'

      - run: cd ./src/Bannerlord.ModuleManager.TypeScript && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}
